### ISSUE TITLE
Error: values don't meet the specifications of the schema(s) in the following chart(s)

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-helm#9]
$ helm install klustair-app klustair/klustair -n klustair-scan
Error: values don't meet the specifications of the schema(s) in the following chart(s):
klustair:
EOF

Happens on last commit:
https://github.com/klustair/klustair-helm/commit/516d5bbe8ac3042e10972389fe63f665c139c4de

**Comment by hugodopradofernandes** [comment]
Solved, thanks!!

$ helm install klustair-app klustair/klustair -n klustair-scan
NAME: klustair-app
LAST DEPLOYED: Tue Nov 17 19:54:22 2020
NAMESPACE: klustair-scan
STATUS: deployed
REVISION: 1

-----------
Default image was reverted back to v0.2.2 on values.yaml. 
Other than that it's working using  --set image.tag=v0.2.5

**Comment by mms-gianni** [comment]
Yes, it was changed to v0.2.5 .. but actually its set to "latest", since i think this will be the most common use case.
